### ISSUE TITLE
Negative delta for user error

### ISSUE THREAD

**Issue by emmairwin** [sarahsharp/foss-heartbeat#48]
I am trying to figure out why I get merge errors (in different repos) running    

> python ghstats.py repo name username docs/

Specifically Ive been running into this error which is being called from getRampTime(); 

('Negative delta for user', 'username', 'for', 'merger', 'on', datetime.datetime(2015, 7, 27, 9, 7, 1))
('first contribution was on', datetime.datetime(2015, 8, 26, 20, 57, 25), 'file', 'mozilla-l10n/appstores/issue-103339758/comment-135168390.json')
Traceback (most recent call last):
  File "ghstats.py", line 396, in <module>
    main()
  File "ghstats.py", line 393, in main
    createGraphs(args.owner, args.repository, args.htmldir)
  File "ghstats.py", line 371, in createGraphs
    os.path.join(repoPath, i[0] + 's-frequency.html'))
  File "ghstats.py", line 248, in graphFrequency
    recent = nobots[0][4]

- It appears to be because nextDate - startDate has a negative value. 
- If I remove the offending username records from merge.txt this error does go away, but I end up with another - which means I'm not solving anything :)
- This user for what it's worth, is a staff member (thus frequently listed), I've only seen this with staff name so far, which makes me wonder if there's it's related to a slightly different way of working (and first arrival logic).

**Comment by Ryuno-Ki** [comment]
Hi, @emmairwin,
I am afraid, I'd need a little bit of help from you …
Here's what I did:

```sh
cd
cd src
virtualenv foss-heartbeat --python=/usr/bin/python3.5
cd foss-heartbeat
git clone https://github.com/sagesharp/foss-heartbeat.git src
source bin/activate
cd src
pip install -r requirements.txt  # This complained about being only for python 3.4, but went through nonetheless
python ghscraper.py foss-heartbeat sagesharp myaccesstoken  # Obviously myaccesstoken needs to be replaced by yours
python ghcategorize.py foss-heartbeat sagesharp
python ghstats.py foss-heartbeat sagesharp docs/
```
All of those worked flawlessly.

In order to properly reproduce it I would either need the repo associated with `mozilla-l10n/appstores/issue-103339758/comment-135168390.json'` or that file itself.

**Comment by emmairwin** [comment]
yes!  I can give you those

for this issue:  

https://github.com/mozilla-l10n/appstores
https://github.com/mozilla-l10n/styleguides 
https://github.com/mozilla-l10n/mozilla.org

I ran these commands:

python ghscraper.py appstore mozilla-l10n [mytokenid]

 python ghcategorize.py appstores mozilla-l10n

 python ghstats.py appstores mozilla-l10n docs/

**Comment by Ryuno-Ki** [comment]
Confirmed.
The Index Error is thrown, because `nobots == []` in that case. I am looking into why …

**Comment by Ryuno-Ki** [comment]
@emmairwin One last thing to help the maintainer fix this issue: Could you upload the following files?
* `mozilla-l10n/appstores/first-interactions.txt`
* `mozilla-l10n/appstores/responders.txt`
* `mozilla-l10n/appstores/mergers.txt`
* `mozilla-l10n/appstores/reporters.txt`
* `mozilla-l10n/appstores/reviewers.txt`

@sagesharp Steps to reproduce:
Drop the above files in `mozilla-l10n/appstores`.
Then open a python shell and run:
```python
from ghstats import createGraphs
createGraphs('mozilla-l10n', 'appstores', 'docs/')
```

**Comment by emmairwin** [comment]
[first-interactions.txt](https://github.com/sagesharp/foss-heartbeat/files/1733045/first-interactions.txt)
[mergers.txt](https://github.com/sagesharp/foss-heartbeat/files/1733046/mergers.txt)
[reporters.txt](https://github.com/sagesharp/foss-heartbeat/files/1733047/reporters.txt)
[responders.txt](https://github.com/sagesharp/foss-heartbeat/files/1733048/responders.txt)
[reviewers.txt](https://github.com/sagesharp/foss-heartbeat/files/1733049/reviewers.txt)
